describe('Test', () => {
  it('Test Login', () => {
      cy.visit('https://siabdestaxion.com/auth/login');
      cy.get('[name="identifier"]').type('hayujajan');
      cy.get('[name="password"]').type('hayujajan');
      cy.get('.gap-y-6 > .inline-flex').click();
      cy.wait(3000);
      cy.get('[href="/unit/general-journal"] > #sidebar-nav-link').click();
      cy.wait(3000);
      cy.get('a > .inline-flex').click();
      cy.get('#evidence').attachFile(["a.png"]);
      cy.get(':nth-child(1) > .gap-y-2 > .space-y-2 > .flex-column > .justify-end > .flex-col > .flex-row').type("1");
      cy.wait(3000);
      cy.get(':nth-child(2) > .gap-y-2 > .space-y-2 > .flex-column > .justify-end > .flex-col').type("2");
      cy.wait(3000);
      cy.get(':nth-child(1) > :nth-child(2) > .space-y-2').type(2000000);
      cy.wait(3000);
      cy.get(':nth-child(2) > :nth-child(3) > .space-y-2').type(2000000);
      cy.wait(3000);
      cy.get('input[name="description"]').type('test');
      cy.wait(3000);
      cy.get('.grid-flow-col > :nth-child(2) > .space-y-2').click(); // Assuming this opens the date picker
      cy.wait(3000);
      cy.get(':nth-child(1) > :nth-child(5) > .rdp-button_reset').click();
      cy.wait(3000);
      cy.get('div.pt-8 > .inline-flex').click();
      cy.wait(3000);
      cy.get('[data-key="clz9h96dq061wzcs0pfej8mtf.1"] > span').click();
      cy.wait(3000);
      cy.get('.flex-1 > [href="/unit/general-journal"]').click();
      cy.wait(3000);
      cy.get('[data-key="clz8n5yeb09jcgek3bybpl9t8.1"] > span').click();
      cy.wait(3000);
      cy.get('[href="/unit/general-journal/clz8n5yeb09jcgek3bybpl9t8/edit"]').click();
      cy.wait(3000);
      cy.get('.font-medium.border').click();
      cy.wait(3000);
      cy.get('[href="/unit/ledger"] > #sidebar-nav-link').click();
      cy.wait(3000);
      cy.get('[href="/unit/working-trial-balance"] > #sidebar-nav-link > .flex > .font-medium').click();
      cy.wait(3000);
      cy.get('a > .inline-flex').click();
      cy.wait(3000);
      cy.get('a > .inline-flex').click();
      cy.wait(4000);
      cy.get(':nth-child(1) > .gap-y-2 > .space-y-2 > .flex-column > .justify-end > .flex-col > .flex-row > .inline-flex.w-full > .flex > .inline-flex').type(1);
      cy.wait(4000);
      cy.get(':nth-child(2) > .gap-y-2 > .space-y-2 > .flex-column > .justify-end > .flex-col > .flex-row > .inline-flex.w-full > .flex > .inline-flex').type(4);
      cy.wait(4000);
      cy.get(':nth-child(1) > :nth-child(2) > .space-y-2').type(300000);
      cy.wait(4000);
      cy.get(':nth-child(2) > :nth-child(3) > .space-y-2').type(300000);
      cy.wait(4000);
      cy.get('input[name="description"]').type('test');
      cy.wait(4000);
      cy.get('.grid-flow-col > :nth-child(2) > .space-y-2').click(); // Assuming this opens the date picker
      cy.wait(4000);
      cy.get(':nth-child(1) > :nth-child(6) > .rdp-button_reset').click();
      cy.wait(4000);
      cy.get('div.pt-8 > .inline-flex').click();
      cy.wait(4000);
      cy.get('#sidebar-navs-laporan-keuangan > :nth-child(1)').click();
      cy.wait(4000);
      cy.get('[href="/unit/financial-statement/income-statement"] > #sidebar-nav-link > .flex > .font-medium').click();
      cy.get('#date').click();
      cy.wait(4000);
      cy.get('.rdp-caption_start > .border-collapse > .rdp-tbody > :nth-child(1) > :nth-child(5) > .rdp-button_reset').click();
      cy.wait(4000);
      cy.get('#date').click();
      cy.wait(4000);
      cy.get('[href="/unit/financial-statement/statement-of-financial-position"] > #sidebar-nav-link > .flex > .font-medium').click();
      cy.wait(4000);
      cy.get('#date').click();
      cy.wait(4000);
      cy.get('.rdp-caption_start > .border-collapse > .rdp-tbody > :nth-child(1) > :nth-child(5) > .rdp-button_reset').click();
      cy.wait(4000);
      cy.get('[href="/unit/financial-statement/calk"] > #sidebar-nav-link > .flex').click();
      cy.wait(4000);
      cy.get('a > .inline-flex').click();
      cy.wait(4000);
      cy.get('.w-fit > .inline-flex').click();
      cy.wait(4000);
      cy.get('[data-key="clz59a9iu000813rsjpjf3oll.1"] > span').click();
      cy.wait(5000);
      cy.get('.bg-secondary').click();
      cy.wait(4000);
      cy.get('#sidebar-navs-data-master > :nth-child(1)').click();
      cy.wait(4000);
      cy.get('#akun > #sidebar-nav-link > .flex').click();
      cy.wait(4000);
      cy.get('a > .inline-flex').click();
      cy.wait(4000);
      cy.get('header > .inline-flex').click();
      cy.wait(4000);
      cy.get('#sidebar-navs-data-master > #sidebar-navs-childs-container > #ppn > #sidebar-nav-link').click();
      cy.wait(5000);
      cy.get('a > .inline-flex').click();
      cy.wait(5000);
      cy.get('header > .inline-flex').click();
      cy.wait(5000);
      cy.get('#sidebar-navs-perpajakan > :nth-child(1) > .flex').click();
      cy.wait(5000);
      cy.get('#sidebar-navs-perpajakan > #sidebar-navs-childs-container > #ppn > #sidebar-nav-link').click();
      cy.wait(5000);
      cy.get('a > .inline-flex').click();
      cy.wait(5000);
      cy.get('.flex-1 > :nth-child(1) > .inline-flex').click();
      cy.wait(5000);
      cy.get('[data-key="clzcchqai000dbo5wzknyp46oclzcchqai000dbo5wzknyp46ogiven_to"] > span').click();
      cy.wait(5000);
      cy.get('a.inline-flex').click();
      cy.wait(5000);
      cy.get('[data-key="clzcchqai000dbo5wzknyp46oclzcchqai000dbo5wzknyp46ogiven_to"] > span').click();
      cy.wait(5000);
      cy.get('.border > .flex').click();
      cy.wait(5000);
      cy.get('.w-fit > .inline-flex').click();
      cy.wait(5000);
      cy.get('#sidebar-navs-perpajakan > :nth-child(1) > .flex').click();
      cy.wait(5000);
      cy.get('#pph21 > #sidebar-nav-link > .flex').click();
      cy.wait(5000);
      cy.get('.justify-between > :nth-child(2)').click();
      cy.wait(4000);
      cy.get('.bg-secondary').click();
      cy.wait(5000);
      cy.get('.container').click();
      cy.wait(5000);
      cy.get('.inline-flex > .text-sm').click();
  })
})